shopify tests
vita-galindoma/sql_training_vg pull request #2
Opened 2021-09-10 11:20 UTC by vita-galindoma

2021-09-11 18:22 UTC, ausmoons requested changes
Testi iziet, bet vajag izņemt liekos failus, komentārus

2021-09-11 18:22 UTC, ausmoons commented on sql-shopify/src/queries/select.ts
> +
db/06-database.sqlite3..  ir lieki faili

2021-09-11 18:22 UTC, ausmoons commented on sql-shopify/test/05-integrity.test.ts
> +        // const query = `DELETE FROM ${APPS} WHERE id = ${appId}`;
?

2021-09-11 18:22 UTC, ausmoons commented on sql-shopify/test/06-update-statement.test.ts
> +        //     if (row.title !== row.title.toUpperCase()) {
?

2021-09-14 17:42 UTC, ausmoons requested changes

2021-09-14 17:42 UTC, ausmoons commented on sql-shopify/src/queries/select.ts
> +
Vēl joprojām ir lieki faili

2021-09-14 19:27 UTC, vita-galindoma commented on sql-shopify/src/queries/select.ts
> +
Vai vari, lūdzu, precizēt, kurā failā ir lieki faili? Jo gan queries/select, gan 06 testā ir viss izmantotais tikai.

https://github.com/vita-galindoma/sql_training_vg/blob/main/sql-shopify/test/06-update-statement.test.ts
https://github.com/vita-galindoma/sql_training_vg/blob/main/sql-shopify/src/queries/select.ts

2021-09-17 18:53 UTC, ausmoons requested changes
![image](https://user-images.githubusercontent.com/53189160/133839558-be01bb44-723e-4bca-ac66-52ef65db713a.png)
Sie ir lieki fali

2021-09-22 19:35 UTC, ausmoons approved these changes

2021-09-24 06:54 UTC, merged